Countdown 5
Countdown 4
Countdown 3
Countdown 2
Countdown 1
Traceback (most recent call last):
  File "demo.py", line 25, in <module>
    run()
  File "demo.py", line 23, in run
    raise IOError("Fake error")
IOError: Fake error
